
# Whether to print progress
print-progress: false

rename:
  # Renaming method: api, regex, or mix
  method: mix
  # Whether to show flag information
  flag: false

check:
  # Concurrency
  concurrent: 100
  # Check interval, in minutes
  interval: 10
  # Alive test URL
  alive-test-url: "https://gstatic.com/generate_204"
  # Alive test expect code
  alive-test-expect-code: 204
  # Timeout, in milliseconds
  timeout: 2000
  # Minimum speed, in KB/s
  min-speed: 2048
  # Download test timeout, in seconds
  download-timeout: 10
  # Speed test download size, in MB
  download-size: 50
  # Speed test URL
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # Skip speed test for names matching this regex
  speed-skip-name: 倍率|x\d+
  # Speed test concurrent
  speed-check-concurrent: 1
  # Speed test count
  speed-count: 10
  # Speed save
  speed-save: true
  # Items to check
  items:
    - openai
    - youtube
    - netflix
    - disney

save:
  # Save method: webdav, http, gist, or r2
  method: 
    - webdav
  # Save port
  port: 8080
  # WebDAV
  webdav-url: "https://webdav.company/dav"
  webdav-username: "username"
  webdav-password: "password"
  # GitHub token
  github-token: ""
  # Gist ID
  github-gist-id: ""
  # GitHub API mirror
  github-api-mirror: "https://your-worker-url.com/github"
  # Worker URL
  worker-url: https://your-worker-url.com
  # Worker token
  worker-token: your-worker-token
  # Before save do
  before-save-do:
    - D:\Github\bestsub\doc\scripts\node.js
  # After save do
  after-save-do:
    - D:\Github\bestsub\test\powershell.ps1

# mihomo api
mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
mihomo-api-secret: ""
# Retry count for subscription URLs
sub-urls-retry: 3
# Proxy settings, supports http and socks proxies
proxy:
  type: "http" # Options: http, socks
  address: "http://192.168.31.11:7890" # Proxy address
# Subscription URLs
# type-include:
#   - ss
#   - vmess
sub-urls:
  - https://example.com/sub1
  - https://example.com/sub2
# Provider filter file
provider-file: providers.yaml
